// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace HelloWorldExtension;

internal sealed partial class Vsix
{
    public const string Id = "HelloWorldExtension.3884086f-2626-4436-a839-03d1bcd248e6";
    public const string Name = "HelloWorldExtension";
    public const string Description = @"Empty VSIX Project.";
    public const string Language = "en-US";
    public const string Version = "1.0";
    public const string Author = "Steven Kirk";
    public const string Tags = "";
}
